apiVersion: v1
kind: Pod
metadata:
  name: testcontainer
  namespace: default
spec:
  containers:
  - image: busybox:1.0.0
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always