apiVersion: v1
kind: Pod
metadata:
  name: foo
  namespace: prod 
spec:
  containers:
  - image: busybox:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
