apiVersion: v1
kind: Pod
metadata:
  name: testcontainer2
  namespace: default
spec:
  containers:
  - image: busybox:2.2.2
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always