apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.name }}
  namespace: default
spec:
  containers:
  - image: busybox:{{.Values.version}}
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
